name: Qualia
favicon: null
layout_spectrum: 0.6707751275971532
typography_spectrum: 0.04077140288427472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9255383682902902
  lightness: 0.3509622428100556
  saturation: 0.20667566289193928
  rhythmicContrast: 0.4881254762876779
purpose: []
